### ISSUE TITLE
Different Results to Blog

### ISSUE THREAD

**Issue by idontgetoutmuch** [lehins/haskell-benchmarks#3]
![image](https://user-images.githubusercontent.com/1550265/74173149-7d6eb980-4c29-11ea-857a-0cc0cb33142e.png)

**Comment by idontgetoutmuch** [comment]
How are you getting the parallelism?

**Comment by lehins** [comment]
@idontgetoutmuch Can you run this on your machine?
```
$ stack bench --ba '--output finalists.html --match pattern Finalists/Word64'
```

And just post a screenshot here?

I just did it on my computer:
![image](https://user-images.githubusercontent.com/2333894/74174401-f16a8b00-4c44-11ea-97a3-97de2f8ed345.png)

**Comment by lehins** [comment]
@idontgetoutmuch I wonder more how come are you not getting it :/ 
> How are you getting the parallelism?

**Comment by idontgetoutmuch** [comment]
I am not using stack - I ran

```
ghc -O2 -threaded -rtsopts -with-rtsopts=-N bench/Random.hs -o benchmark -isrc -fforce-recomp
./benchmark +RTS -N8
```

and now everything looks a lot better.

![image](https://user-images.githubusercontent.com/1550265/74176930-975fca80-4c30-11ea-9e12-3dfd114ee310.png)

**Comment by lehins** [comment]
Now that's more like it :)

Common, Dominic, you missing out man! ;P
> I am not using stack

**Comment by idontgetoutmuch** [comment]
I use nix for everything these days :) I am going to create a PR as you suggest in your blog unless you'd like to create it yourself.

**Comment by idontgetoutmuch** [comment]
I'm going to run `testu01` first though - I imagine some tests might fail but by definition all PRNGs will fail some test of randomness.

**Comment by lehins** [comment]
@idontgetoutmuch Sorry I am not following, which PR did I suggest?

**Comment by idontgetoutmuch** [comment]
- Switch random package to depend on splitmix, instead of the other way round. Get rid of the internal StdGen implementation in favor of SMGen (i.e. type StdGen = SMGen).
- Improve the implementation of each individual instance of Random
- Make it possible for implementers of custom generators to override default implementations of individual primitive types (i.e. customizable random function).
- Add an interface to random package for stateful generators, which could be used by mwc-random and others alike.

**Comment by idontgetoutmuch** [comment]
Perhaps we can chat about this somehow rather than using a ticket?

**Comment by lehins** [comment]
@idontgetoutmuch Absolutely!! That's awesome. I though I was shouting out into the abyss. I wonder if @cartazio is gonna be opened to merging such PR? I am not interested in forking `random`. So if everyone is onboard I'll pitch in as well. Fixing `random` would have a huge positive effect on the Haskell ecosystem, especially on testing.

We can schedule something like hangouts. You can always get a hold of me here: https://gitter.im/haskell-massiv/Lobby, ZuriHac slack and on [Keybase](https://keybase.io/lehins)
